services:
  backend:
    build: .
    container_name: backend
    networks:
      - news_network
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn app.backend.server:app --host 0.0.0.0 --port 8000

  frontend:
    build: .
    container_name: frontend
    networks:
      - news_network
    ports:
      - "8501:8501"
    depends_on:
      - backend
    volumes:
      - .:/app
    command: streamlit run app/frontend/app.py --server.port=8501 --server.address=0.0.0.0

networks:
  news_network:
    driver: bridge